// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveResource(arg1) {
  return window['go']['desktop']['App']['ArchiveResource'](arg1);
}

export function CreateCategory(arg1, arg2) {
  return window['go']['desktop']['App']['CreateCategory'](arg1, arg2);
}

export function CreateReminder(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['CreateReminder'](arg1, arg2, arg3, arg4);
}

export function CreateResource(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['CreateResource'](arg1, arg2, arg3, arg4);
}

export function CreateTodo(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['CreateTodo'](arg1, arg2, arg3, arg4);
}

export function DeleteCategory(arg1) {
  return window['go']['desktop']['App']['DeleteCategory'](arg1);
}

export function DeleteReminder(arg1) {
  return window['go']['desktop']['App']['DeleteReminder'](arg1);
}

export function DeleteResource(arg1) {
  return window['go']['desktop']['App']['DeleteResource'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['desktop']['App']['DeleteTodo'](arg1);
}

export function GetCategories() {
  return window['go']['desktop']['App']['GetCategories']();
}

export function GetReminders(arg1, arg2) {
  return window['go']['desktop']['App']['GetReminders'](arg1, arg2);
}

export function GetResourceByID(arg1) {
  return window['go']['desktop']['App']['GetResourceByID'](arg1);
}

export function GetResources(arg1, arg2) {
  return window['go']['desktop']['App']['GetResources'](arg1, arg2);
}

export function GetTodos(arg1, arg2) {
  return window['go']['desktop']['App']['GetTodos'](arg1, arg2);
}

export function NotifyProcessingComplete(arg1) {
  return window['go']['desktop']['App']['NotifyProcessingComplete'](arg1);
}

export function RestoreResource(arg1) {
  return window['go']['desktop']['App']['RestoreResource'](arg1);
}

export function SearchResources(arg1, arg2) {
  return window['go']['desktop']['App']['SearchResources'](arg1, arg2);
}

export function StartTray() {
  return window['go']['desktop']['App']['StartTray']();
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function UpdateReminder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['desktop']['App']['UpdateReminder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['App']['UpdateResource'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTodo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['desktop']['App']['UpdateTodo'](arg1, arg2, arg3, arg4, arg5, arg6);
}
