// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ArchiveResource(arg1:string):Promise<void>;

export function CreateCategory(arg1:string,arg2:string):Promise<domain.Category>;

export function CreateReminder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Reminder>;

export function CreateResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Resource>;

export function CreateTodo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Todo>;

export function DeleteCategory(arg1:string):Promise<boolean>;

export function DeleteReminder(arg1:string):Promise<boolean>;

export function DeleteResource(arg1:string):Promise<boolean>;

export function DeleteTodo(arg1:string):Promise<boolean>;

export function GetCategories():Promise<Array<domain.Category>>;

export function GetReminders(arg1:number,arg2:number):Promise<Array<domain.Reminder>>;

export function GetResourceByID(arg1:string):Promise<domain.Resource>;

export function GetResources(arg1:number,arg2:number):Promise<Array<domain.Resource>>;

export function GetTodos(arg1:number,arg2:number):Promise<Array<domain.Todo>>;

export function NotifyProcessingComplete(arg1:string):Promise<void>;

export function RestoreResource(arg1:string):Promise<void>;

export function SearchResources(arg1:string,arg2:number):Promise<Array<domain.Resource>>;

export function StartTray():Promise<void>;

export function UpdateCategory(arg1:string,arg2:string,arg3:string):Promise<domain.Category>;

export function UpdateReminder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<domain.Reminder>;

export function UpdateResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<domain.Resource>;

export function UpdateTodo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<domain.Todo>;
